# Try to find the Box2D library
#  BOX2D_FOUND - system has BOX2D
#  BOX2D_INCLUDE_DIR - the BOX2D include directory
#  BOX2D_LIBRARY - the BOX2D library

FIND_PATH(BOX2D_INCLUDE_DIR NAMES box2d/box2d.h)
FIND_LIBRARY(BOX2D_LIBRARY NAMES libbox2d.a libbox2d.so)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Box2D DEFAULT_MSG BOX2D_LIBRARY BOX2D_INCLUDE_DIR)
MARK_AS_ADVANCED(BOX2D_LIBRARY BOX2D_INCLUDE_DIR)
